Repository Financial-Times/o-comments, pull requests merged in 2020-08, with the labels that each got.

#177 Improve error messages from async tests by passing the error to the `done` callback.
  test/comments.test.js
  test/methods/stream/publish-event.js
  test/utils/display-name.test.js
Labels: component

#178 Add general usage to readme
  README.md
Labels: component, release:patch

#180 Use the new $default-branch macro instead of hardcoding the branch name
  .github/workflows/percy.yml
Labels: component

#176 Update CSS that is rendered inside Coral iFrame
  src/scss/coral-talk-iframe/main.scss
Labels: component, release:minor

#179 Update readme to conform to the readme linter
  README.md
Labels: component, documentation, release:patch

#182 Move to Github's native Dependabot
  .dependabot/config.yml
  .github/dependabot.yml
  .github/workflows/automerge.yml
Labels: component

#185 remove the ci section from origami.json and circle badge from the readme
  README.md
  origami.json
Labels: component
